shellcheck and formatted

diff --git a/etoyear b/etoyear
--- a/etoyear
+++ b/etoyear
@@ -2,19 +2,19 @@
 readonly VER='0.0.3'
 readonly CREATE_YEAR='2019'
 readonly AUTHOR='haruna <github.com/eggplants>'
-readonly DEFAULT_YEAR=`date +%Y`
+readonly DEFAULT_YEAR=$(date +%Y)
 readonly DEFAULT_LINE='12'
 readonly ANIMALS_EMOJI=(
-    🐒 🐔 🐕 🐗 🐁 🐄
-    🐯 🐇 🐲 🐍 🐎 🐏
+  🐒 🐔 🐕 🐗 🐁 🐄
+  🐯 🐇 🐲 🐍 🐎 🐏
 )
 readonly ANIMALS_KANJI=(
-    申 酉 戌 亥 子 丑
-    寅 卯 辰 巳 午 羊
+  申 酉 戌 亥 子 丑
+  寅 卯 辰 巳 午 羊
 )
 # help
-function show_help(){
-cat<<EOS
+function show_help() {
+  cat << EOS
 NAME:
     etoyear - show eto-year list
 
@@ -37,8 +37,8 @@ OPTION:
 EOS
 }
 # version
-function show_version(){
-cat<<EOS
+function show_version() {
+  cat << EOS
 etoyear version ${VER}
 Copyright (c) ${CREATE_YEAR} ${AUTHOR}
 Released under the MIT License.
@@ -46,49 +46,60 @@ EOS
 }
 
 # main
-function main(){
-# prosess options(help, version, kanji)
-case "$1" in
+function main() {
+  # prosess options(help, version, kanji)
+  case "$1" in
 
--h|--help)
-    show_help; exit 0;;
--v|--version)
-    show_version; exit 0;;
--k|--kanji)
-    local _animals=("${ANIMALS_KANJI[@]}"); shift;;
--*)
-    echo "ARGUMENT_ERROR::invalid option:$1." 1>&2;exit 1;;
-*)
-    local _animals=("${ANIMALS_EMOJI[@]}");;
+    -h | --help)
+      show_help
+      exit          0
+      ;;
+    -v | --version)
+      show_version
+      exit             0
+      ;;
+    -k | --kanji)
+      local _animals=("${ANIMALS_KANJI[@]}")
+      shift
+      ;;
+    -*)
+      echo "ARGUMENT_ERROR::invalid option:$1." 1>&2
+      exit                                              1
+      ;;
+    *)
+      local _animals=("${ANIMALS_EMOJI[@]}")
+      ;;
 
-esac
+  esac
 
-if [[ "$#" = 0 ]];then
-    if [[ "${_animals[0]}" == "申" ]];then
-        main -k ${DEFAULT_YEAR} ${DEFAULT_LINE}
+  if [[ $# == 0 ]]; then
+    if [[ ${_animals[0]} == "申"       ]]; then
+      main -k "${DEFAULT_YEAR} ${DEFAULT_LINE}"
     else
-	main ${DEFAULT_YEAR} ${DEFAULT_LINE}
+      main "${DEFAULT_YEAR}" "${DEFAULT_LINE}"
     fi
     exit 0
-fi
+  fi
 
-local _year="$1" _times="$(($2-1))"
+  local _year="$1" _times="$(($2 - 1))"
 
-if [[ "$1" -le 0 ]];then
-    echo 'ARGUMENT_ERROR::first argument should be more than 0.' 1>&2;exit 1
-fi
+  if [[ $1 -le 0 ]]; then
+    echo 'ARGUMENT_ERROR::first argument should be more than 0.' 1>&2
+    exit                                                                   1
+  fi
 
-if [[ "$#" = 1 ]];then
-    _times=$((${DEFAULT_LINE}-1))
-elif [[ "$2" -le 0 ]];then
-    echo 'ARGUMENT_ERROR::second argument should be more than 0.' 1>&2;exit 1
-fi
+  if [[ $# == 1 ]]; then
+    _times=$((DEFAULT_LINE - 1))
+  elif [[ $2 -le 0 ]]; then
+    echo 'ARGUMENT_ERROR::second argument should be more than 0.' 1>&2
+    exit                                                                    1
+  fi
 
-local _ind=$((${_year}%12))
+  local _ind=$((_year % 12))
 
-for i in `seq 0 ${_times}`;do
-    echo ${_animals[$(((${_ind}+$i)%12))]}
-done|nl -n ln -s' ' -v "${_year}"
+  for i in $(seq 0 ${_times}); do
+    echo "${_animals[$(((_ind + i) % 12))]}"
+  done | nl -n ln -s' ' -v "${_year}"
 }
-main $@
+main "$@"
 exit $?
